---
title: "Assignment 4, study design"
author: "Annlaug Skarpeid"
format: html
editor: visual
---

**Introduksjon**

I denne oppgaven har jeg valgt fem originale artikler hvor jeg skal se på styrkene og svakhetene omhandlet studienes design og valg av statistiske tester. De fem valgte studiene omhandler muskelkvalitet (MK) innenfor styrketrening. Hvor godt en muskel klarer å løse en oppgave i forhold til størrelsen samt kvaliteten på muskelen sier noe om muskelkvaliteten. Muskelkvalitet er definert som styrke per enhet muskelmasse.[@Ivey2000]. Begrepene muskelkvalitet og spesifikk spenning har lik betydning i denne oppgaven.

**Metode**

Formålet til alle artiklene er innenfor tematikken styrketreningens påvirkning på muskelkvalitet. I studien av Ivey (2000) er formålet å se på alders- og kjønnssammenhenger i responsen av styrketrening på muskelkvaliteten. Dette for å avgjøre om det er andre faktorer enn muskelmasse som påvirker styrke økninger eller tap av styrke hos unge og eldre menn og kvinner.[@Ivey2000]. I studien av Ferrari (2016) er formålet å sammenligne effekten av ulik ukentlig frekvens av samme trening og se på muskelkraft og muskelkvalitet[@Ferrari2016]. Pinto (2014) har som formål å vurdere effekten av et kortvarig styrketreningsprogram på muskelkvaliteten og funksjonskapasitet[@Pinto2014]. Videre har studien til Erskine (2011) som formål å finne ut om en forventet økning i muskelspesifikk spenning (MK) etter styrketrening kan forklares av endringer i muskelens isoformsammensetning og enkeltfiberspesifikk spenning eller en endring i lateral kraftoverføring[@Erskine2011] Siste valgte studie av Tracy (1999) har som formål å sammenligne responsen på muskelkvalitet på en unilateralt quadriceps styrketreningsprogram mellom eldre menn og eldre kvinner[@Tracy1999].

Tre av fem artikler har en tydelig hypotese før datainnsamling, mens de resterende to artiklene tar mer for seg spørsmål de ikke har svar på innenfor temaet, som igjen er en av grunnene til at de har startet studien om tema. Hypotesene er hovedsakelig basert på tidligere kunnskap og tidligere studier. De studiene som hadde en tydelig hypotese kan i følge Hulley (2013) kategoriseres under kliniske studier. Kliniske studier har en mal hvor det å danne flere gode hypoteser på forhånd for å deretter spesifisere en primær hypotese er sentral. Det positive med å ha en primær hypotese er at det kan bli lettere å fokusere innsamlingen av dataen på de faktorene/variablene som kan tilknyttes hypotesen[@designin2013a, s.53] .Ferrari (2016) er et eksempel på en studie som hadde en klar hypotese som var basert på tidligere innsamlinger av data i andre studier og handlet om at styrketrening utført 2 eller 3 ganger i uken vil gi lik muskeltilpasning. Et eksempel på en studie som hadde spørsmål istedenfor hypoteser var Ivey (2000) der de ønsker å få svar på om alder eller kjønn påvirker MK og hva som skjer etter opphør av styrketrening, og om nedgang i muskelaktivitet bidrar til aldersrelatert nedgang av MK.

Metoden de ulike studiene brukte for å rekruttere deltakerne til studiene var tilnærmet likt. Grunnlaget for alle studiene var at deltakerne fikk god informasjon om studiene i forkant, de måtte gi skriftlig samtykke, det var frivillig og alle hadde gjennomgått en sykehistorikk og hatt fysiske undersøkelser. Alle studiene har også blitt godkjent av ulike universitet og medisinske senter. Forskjellene mellom studiene var at noen hadde litt ulike krav i forholdt til om deltakerne skulle være utrente eller trente og graden av erfaring i forkant, noe som står beskrevet i studiene. Populasjonen eller deltakerne i alle studiene er beskrevet med alder ± x år og kjønn. Det er også informert om hvordan de har utelukket deltakere grunnet deres ulike sykdommer, medisiner eller fysiske plager. Fire av fem studier tar for seg en populasjon over 65 år hvor den ene studien har deltakere i alder rundt 20 år.

Samtlige studier har en pre og en post test hvor testingen er lik med blant annet samme utstyr, samme tid på døgnet, samme forsker og lik tid mellom øvelsene. De bruker derimot ulikt statistiske tester for å se forskjellene fra før og etter intervensjonen med styrketrening. Studiene av Ivey (2000) og Tracy (1999) tar MR av quadriceps både pre og post, samt 1RM. Erskine (2011) tar også MR men tok også muskelbiopsi og anatomisk tverrsnittsarial kalt «ACSA» for å estimere MK i quadricepsen. Studiene av Ferrari (2016) og Pinto (2014) tar ultralyd av muskeltykkelse, samt 1RM. Bare studiene av Ivey (2000), Ferrari (2016) og Tracy (1999) nevnte at de hadde utprøving av testingen i forkant for å unnvike læringseffekten og for å forebygge skader. Dette kan imidlertidig også føre til redusert størrelse på forandringene på pre og post, da de får testet ut øvelsene før testen starter.

Variasjonsanalysen kalt «ANOVA» ble tatt i bruk i samtlige studier hvor de sammenligner pre og post i gjennomsnitt i ulike grupper. Studien av Ferrari (2016) hadde også en crossover randomisert klinisk studie hvor deltakerne ble tilfeldig delt inn i 2 grupper. Deltakerne skulle dermed enten trene 2 ganger i uken eller 3 ganger i uken. Begge gruppene hadde samme intensitet og volum under treningene til tross for ulike treningsdager, samt tett veiledet av minst to erfarne personlige trenere. Både Ferrari (2016), Tracy (1999) og Pinto (2014) brukte SPSS for å analysere data.

**Resultat**

Til tross for at alle studiene hadde ulik tilnærming i form av antall reps og serier, samt ulik kombinasjon av antall deltakere, alder og kjønn, fikk alle et resultat som indikrer en viss prosent økning i MK etter styrketrening. Alle som hadde en klar hypotese, fikk enten bekreftet eller avkreftet den etter datainnsamlingen. Til tross for dette fikk ikke alle studiene svar på alt de lurte på.

Artikkelen av Ferrari (2016) hadde en klar hypotese i forkant av studien og fikk til resultat at styrketrening utføre 2 ganger i uka ga 8% økning i MK sammeligent med styrketrening 3 ganger i uken som ga 15% økning i MK @Ferrari2016 . Studien av Pinto (2014) hadde en hypotese som ble bekreftet som handlet om at 6 ukers styrketrening vil resultere i markerte gevinster innenfor muskeltykkelse og MK @Pinto2014 . Hypotesen til studien av Tracy (1999) viste seg å være feil da det ikke var en betydelig forskjell mellom kjønn på MK @Tracy1999 . Spørsmålet i artikkelen av Erskine (2011) ble besvart med at muskelspesifikk spenning øker etter styrketrening hvorav et eksempel på en av de mulige årsakene var at det var en økning i lateral kraftoverføring fra sarkomerer i muskelfibrene. Et eksempel på et spørsmål de ikke fikk svar på var om det var noen sammenheng mellom isoformsammensetning og økning i muskelspesifikk spenning @Erskine2011 . Studien av Ivey (2000) hadde blant annet spørsmål angående kjønns og aldres påvirkning på MK, hvor resultatet tyder på at det er økning i MK i begge kjønn både hos unge og eldre @Ivey2000 .

*Vedlagt er en tabell over alle studiene hvor diverse informasjon om deltakerne, studiedesign og resultat er representert.*

+------------+------------------------+-----------------------------------------------+-----------------------------------------------------+---------------------------------------------------------------------------------------------+
|            | Studie                 | Deltakere                                     | Studiedesign                                        | Resultat                                                                                    |
+============+========================+===============================================+=====================================================+=============================================================================================+
| 1\.        | Ivey, et al. (2000)    | 42 deltakere:\                                | 9 uker styrketrening og 31 ukers "nedtrapping":     | Økning i muskelkvalitet blant unge og gamle (begge kjønn)                                   |
|            |                        | Unge menn og kvinner og eldre menn og kvinner |                                                     |                                                                                             |
|            |                        |                                               | 5-10 reps\                                          |                                                                                             |
|            |                        | 20-30 år og 65-75 år                          | 5 serier\                                           |                                                                                             |
|            |                        |                                               | 3 ganger i uka                                      |                                                                                             |
|            |                        |                                               |                                                     |                                                                                             |
|            |                        |                                               | Bein- og kneekstensjon                              |                                                                                             |
|            |                        |                                               |                                                     |                                                                                             |
|            |                        |                                               | MR.                                                 |                                                                                             |
+------------+------------------------+-----------------------------------------------+-----------------------------------------------------+---------------------------------------------------------------------------------------------+
| 2\.        | Ferrari, et al (2016)  | 24 deltakere:\                                | 20 uker trening og 10 uker intervensjon:            | -   2 ganger i uka: 8%økning i MK                                                           |
|            |                        | Eldre trente menn                             |                                                     |                                                                                             |
|            |                        |                                               | 8-12 reps\                                          | -   3 ganger i uka:\                                                                        |
|            |                        | 65±4 år                                       | 3 serier\                                           |     15% økning i MK                                                                         |
|            |                        |                                               | 2 eller 3 ganger i uka (2 ulike grupper)            |                                                                                             |
|            |                        |                                               |                                                     |                                                                                             |
|            |                        |                                               | Bein/ekstensorer                                    |                                                                                             |
|            |                        |                                               |                                                     |                                                                                             |
|            |                        |                                               | Ultralyd.                                           |                                                                                             |
+------------+------------------------+-----------------------------------------------+-----------------------------------------------------+---------------------------------------------------------------------------------------------+
| 3\.        | Pinto, et al. (2014)   | 36 deltakere:\                                | 6 uker:                                             | 15% økning i MK i quadriceps                                                                |
|            |                        | Eldre kvinner                                 |                                                     |                                                                                             |
|            |                        |                                               | 12-15 reps\                                         |                                                                                             |
|            |                        | 66±8 år                                       | 2-3 serier\                                         |                                                                                             |
|            |                        |                                               | 2 ganger i uka                                      |                                                                                             |
|            |                        |                                               |                                                     |                                                                                             |
|            |                        |                                               | Kneekstensjon                                       |                                                                                             |
|            |                        |                                               |                                                     |                                                                                             |
|            |                        |                                               | Ultralyd.                                           |                                                                                             |
+------------+------------------------+-----------------------------------------------+-----------------------------------------------------+---------------------------------------------------------------------------------------------+
| 4\.        | Erskine, et al. (2011) | 42 deltakere:\                                | 9 uker:                                             | 11%økning i MK (spesifikk tensjon)                                                          |
|            |                        | Unge menn                                     |                                                     |                                                                                             |
|            |                        |                                               | 10 reps\                                            |                                                                                             |
|            |                        | 20 ±3 år                                      | 4 serier\                                           |                                                                                             |
|            |                        |                                               | 80%av 1RM\                                          |                                                                                             |
|            |                        |                                               | 3 ganger i uka                                      |                                                                                             |
|            |                        |                                               |                                                     |                                                                                             |
|            |                        |                                               | bein- kneekstensjon                                 |                                                                                             |
|            |                        |                                               |                                                     |                                                                                             |
|            |                        |                                               | MR.                                                 |                                                                                             |
+------------+------------------------+-----------------------------------------------+-----------------------------------------------------+---------------------------------------------------------------------------------------------+
| 5\.        | Tracy, et al. (1999)   | 23 deltakere:\                                | 9 uker:                                             | Betydelig økning i MK i begge gruppene                                                      |
|            |                        | 12 eldre menn og 11 eldre kvinner             |                                                     |                                                                                             |
|            |                        |                                               | 5 serier:\                                          | Ingen kjønnsforksjeller i MK hos eldre; de foreslår nevromuskulære årsaker i begge gruppene |
|            |                        | 65-75 år                                      | -1: oppvarming, 5 rep (50% av 1RM)\                 |                                                                                             |
|            |                        |                                               | -2: 5 rep (5RM)\                                    |                                                                                             |
|            |                        |                                               | -3: 10 reps (5 rep på 5RM og 5 rep på mindre vekt)\ |                                                                                             |
|            |                        |                                               | -4 og 5: 5 rep (5RM) + 10 rep (som nr.3)\           |                                                                                             |
|            |                        |                                               | 3 ganger i uka                                      |                                                                                             |
|            |                        |                                               |                                                     |                                                                                             |
|            |                        |                                               | Leg ekstensjon + 1RM i leg ekstensjon               |                                                                                             |
|            |                        |                                               |                                                     |                                                                                             |
|            |                        |                                               | MR.                                                 |                                                                                             |
+------------+------------------------+-----------------------------------------------+-----------------------------------------------------+---------------------------------------------------------------------------------------------+
|            |                        |                                               |                                                     |                                                                                             |
+------------+------------------------+-----------------------------------------------+-----------------------------------------------------+---------------------------------------------------------------------------------------------+

**Diskusjon**

Samtlige studier konkluderte, som sagt tidligere, med at det er en tydelig økning i muskelkvalitet etter styrketrening. I tabellen ovenfor vises alle resultatene fra studiene, og ut ifra tabellen kan vi se at styrketrening med mellom 8-15 reps, 3 serier og 2-3 ganger i uka ga en positiv innvirkning på muskelkvaliteten. Det kom også frem at alle deltakerne uavhengig av kjønn og alder fikk økt muskelkvalitet. Det kan derimot være vanskelig å konkludere med hvilke antall repetisjoner og serier som er optimalt for hver gruppe med tanke på å øke muskelkvaliteten da alle studiene har ulikt antall. Til videre forskning ville det derfor kanskje vært interresant å undersøke om hvilke sammensetning av repetisjoner og serier som gir mest økning i muskelkvalitet.

Alle studiene hadde en god beskrivelse av deltakerne som var med, samt hvem de hadde utelatt grunnet fysiske utfordringer. Alle deltagerne hadde fått god og rikelig med informasjon i forkant av studien. Begrunnelsene for valg av alder i studiene hadde sterk sammenheng med hypotesen i forkant av datainnsamlingene. Fire av studiene hadde 65+ år som deltakere, og alle konkluderte med at det som kommer med alderdommen kan påvirke styrken og muskelkvaliteten [@Ferrari2016; @Ivey2000; @Pinto2014; @Tracy1999]. Studiene hadde et antall deltakere fra 23 til 42. En større andel deltakere ville gitt større statistisk styrke, grunnet flere observasjoner som kan påvirke studienes resultater. Ivey (2000), Pinto (2014), Erskine (2011) og Tracy (1999) har tatt i bruk p-verdi hvor samtlige hadde et signifikansnivå under 0.05 (P \< 0.05). Ferrari (2016) tok i bruk alpha for å vise til at studien var signifikant ved a= 0.05. Både Erskine (2011) og Ferrari (2016) hadde også tatt i bruk t-test for å sammenligne belastningene før og etter styrketreningen for hver pulje. Både verdiene til p-verdien på 0.05 og alpha på 0.05 er innenfor grensen som bedømmer om en studie er signifikant eller ikke. Noe som indikerer at det er under 5% sannsynlig for at resultatene i alle studiene er tilfeldige.

De studiene som hadde en hypotese i forkant, tok denne med inn i resultat og diskusjonsdelen. Det var både bekreftelse og avkreftelse av hypoteser. Det var ikke alle studiene som hadde lagt fram ønske om videre forskning i diskusjonsdelen. Studiene av Ivey (2000) og Tracy (1999) la blant annet frem at de ikke fant noen tydelig forskjell på økt muskelkvalitet mellom kjønn og Ferrari (2016) kunne konkludere med at det var tilnærmet lik økning i muskelkvalitet om du trente to eller tre dager i uka. Studien av Pinto (2014) legger fram resultat om økt muskelkvalitet hos eldre kvinner etter et kortvarig styrketreningsprogram. Da deltakerne er 65+ kan aldersrelaterte plager spille inn på motivasjonen og tidsbruk. Resultatene indikerer derfor at eldre menn og kvinner behøver bare å trene 2 ganger i uka, samt at det gir rask forbedring som kan øke motivasjonen og muligheten for å vedlikeholde styrken, da styrke er veldig viktig for eldre mennesker å vedlikeholde for å kunne utføre daglige aktiviteter og gjøremål. [@Ferrari2016; @Pinto2014]. Erskine (2011) hadde en studie om unge menn hvor resultatet viste til en økning i muskelkvalitet og muskelstyrke, til tross for det ble musklene også langsommere. Resultatet omhandlet at musklene ble langsommere uttrykker Erskine (2011) nødvendigheten med ytterligere arbeid for å kunne besvare resultatet.

For at videre undersøkelser skal kunne få best mulig svar på lignende spørsmål som de nevnte studiene vil blant annet det å arbeide nøyaktig i gjennomføringen av testene og eventuelt lab arbeid være viktig, samt standardisere protokollene slik at gjennomføringen er mest mulig likt for hver gang for at testene skal kunne være reliabel. I alle studiene var MR og ultralyd den statistiske metoden for å måle muskelkvalitet pre og post intervensjonen. To av fem studier har benyttet ultralyd som statistisk test og tre av fem studier brukte MR. Man kan i større grad skille mellom muskulatur, fettvev og andre vev med MR enn ultralyd, noe som kan gi et mer nøyaktig og konkret svar. Da en MR tar mer nøyaktige bilder i forhold til tema omhandlet muskelkvalitet vil den gi et mer konkret svar og det vil sannsynligvis bli mindre målefeil og andre feilmarginer. Jeg har fått inntrykk av at alle studiene har hatt god planlegging og gjennomføring med tanke på reliabilitet og validitet da det var like pre og post tester, og de ble gjennomført på tilnærmet lik måte. Ut ifra studiene jeg har valgt fikk de med hypotese et tydeligere svar enn de som bare hadde spørsmål da den enten blir bekreftet eller avkreftet. Derfor mener jeg at det er en fordel å ha en tydelig hypotese før innsamling av data for å kunne systematisere data og ha mer fokus på variabler tilknyttet hypotesen.
